services:
  - type: web
    name: fastapi-example
    runtime: python3
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}